namespace CredECard.Common.BusinessService
{
    public enum EnumFieldErrorConstants
    {
        AMOUNT = 1,
        Debtor_ACCOUNT = 2,
        Creditor_ACCOUNT = 3,
        Customer_ACCOUNT = 4,
        ACCOUNT = 5,
        FTP_SERVER = 6,
        FTP_USER_NAME = 7,
        USER_NAME = 8,
        FTP_TYPE = 9,
        FTP_PASSWORD = 10,
        KEY_TYPE = 11,
        SECRET_KEY = 12,
        KEY_VALUE = 13,
        KEY_DESCRIPTION = 14,
        ERROR_OCCURED_DATE = 15,
        FILENAME = 16,
        DESCRIPTION = 17,
        HOLIDAY_DESCRIPTION = 18,
        FILE_PATH = 19,
        GROUP_NAME = 20,
        BANKTYPECODE = 21,
        PROVIDER = 22,
        PROVIDER_ID = 23,
        DIRECT_DEBIT_INSTRUCTION = 24,
        TRANSACTION_TYPE = 25,
        USER_IDENTIFIER = 26,
        USER = 27,
        USER_ID = 28,
        USERNAME_OR_EMAIL = 29,
        OLD_PASSWORD = 30,
        ACCOUNT_IDENTIFIER = 31,
        ACCOUNT_MANDATES = 32,
        REQUEST_BODY = 33,
        INSTITUTION_CODE = 34,
        SORT_CODE = 35,
        INSTITUTION_ID = 36,
        USERNAME_OR_PASSWORD = 37,
        PASSWORD = 38,
        PASSWORD_EXPIRY_DATE = 39,
        ROLE_ID = 40,
        MANDATE_TYPE = 41,
        HOLIDAY_DATE = 42,
        TRANSACTION = 43,
        WEBHOOK_ID = 44,
        WEBHOOK_URL = 45,
        CERTIFICATE_IDENTIFIER = 46,
        CERTIFICATE_NAME = 47,
        CERTIFICATE_KEY = 48,
        START_DATE = 49,
        EXPIRY_DATE = 50
    }
}
