version: '3.4'

services:
  
  #accountprocessservice.api:
  #  container_name: accountprocessservice.api
  #  environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - DOTNET_RUNNING_IN_CONTAINER=true
  #     - "ConnectionStrings:DefaultConnection=Server=localhost/SQLEXPRESS;Database=AgencyDB;Trusted_Connection=True;MultipleActiveResultSets=true;"
  #     - "ElasticConfiguration:Uri=http://localhost:9200"
  #  ports:
  #     - "6102:80"

  agencyservice.api:
    container_name: agencyservice.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DOTNET_RUNNING_IN_CONTAINER=true
        - "ConnectionStrings:DefaultConnection=Server=localhost/SQLEXPRESS;Database=AgencyDB;Trusted_Connection=True;MultipleActiveResultSets=true;"
        - "ElasticConfiguration:Uri=http://localhost:9200"
    ports:
        - "6101:80"
